FROM ubuntu:22.04
LABEL author="James Cherry"
LABEL maintainer="James Cherry <cherry@parallaxsw.com>"

# Install basics
RUN 
RUN sed -i "s/archive.ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    tzdata \
    wget \
    cmake \
    gcc \
    g++ \
    tcl-dev \
    tcl-tclreadline \
    libeigen3-dev \
    swig \
    bison \
    flex \
    automake \
    autotools-dev

# Download CUDD
RUN wget --no-check-certificate \
    https://raw.githubusercontent.com/davidkebo/cudd/main/cudd_versions/cudd-3.0.0.tar.gz && \
    tar -xvf cudd-3.0.0.tar.gz && \
    rm cudd-3.0.0.tar.gz

# Build CUDD
RUN cd cudd-3.0.0 && \
    mkdir ../cudd && \
    ./configure && \
    make -j`nproc`

# Copy files and install OpenSTA
RUN mkdir OpenSTA
COPY . OpenSTA
RUN cd OpenSTA && \
    rm -rf build && \
    mkdir build && \
    cd build && \
    cmake -DCUDD_DIR=../cudd-3.0.0 .. && \
    make -j`nproc`

# Run sta on entry
ENTRYPOINT ["OpenSTA/build/sta"]
